### ISSUE TITLE
Configure prometheus for CTA

### ISSUE THREAD

**Issue by ericvaandering** [FNAL-CTA/CTAEvaluation#16]
Several things needed after getting cloud prober running:

Example job. Here we add the cta flavor value as an instance
```
  - job_name: 'poms'
    metrics_path: '/poms/metrics'
    static_configs:
      - targets: ['hostname and port']
        labels:
          instance: dev
      - targets: ['hostname and port']
        labels:
          instance: prod
```

In the job? rewrite the metrics to add cta_
```
    relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        replacement: cta_$1
```
and finally send them off to landscape

```
global:
  external_labels:
      monitor: 'cta'

remote_write:
  - url: "http://hostname:9009/api/v1/push"
  ```

Se notes for the hostnames
